---
swagger: "2.0"
info:
  description: "This is a the Coffee Checkout Validator Server.  You can find out more  here: https://git.thm.de/web-t/coffee-data-service "
  version: "1.0.5"
  title: "Swagger Coffee Checkout Validator Service"

host: "localhost:8084"
basePath: "/"
tags:
- name: "Cart"
  description: "Everything about your cart"
schemes:
- "http"

paths:
  /cart:
    get:
      tags:
      - "cart"
      summary: "Welcome Text"
      description: ""
      operationId: "getProducts"
      responses:
        200:
          description: "successful operation"
    post:
      tags:
      - "cart"
      summary: "check cart total cost"
      description: ""
      operationId: "check cart"
      parameters:
        - in: body
          name: total
          schema:
            type: '#/components/schemas/Cartcost:'
            example: { "total": 10.1 }
          required: true
          description: Numeric key value pair of the checkout total cost
      responses:
        200:
          description: "successful operation"
          schema:
            type: string
            example: 'invalid'
  /:
    get:
      tags:
      - "cart"
      summary: "Welcome Text"
      description: "Welcomes You"
      operationId: "welcome"
      responses:
        200:
          description: "successful operation"
   
definitions:
  Cartcost:
    type: "object"
    required:
    - "total"
    properties:
      total:
        type: "number"
        format: "float"
